version: '3.5'

networks:
  app_network:
    name: app_network
    driver: bridge

services:

  php:
    container_name: max_php
    build:
      context: ./docker/php
    networks:
      - app_network
    volumes:
      - ./src:/app

  nginx:
    container_name: max_nginx
    image: nginx:latest
    networks:
      - app_network
    ports:
      - 8099:80
    volumes:
      - ./src:/app
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  mysql:
    container_name: max_mysql
    image: mysql:latest
    networks:
      - app_network
    ports:
      - 3399:3306
    volumes:
      - ./docker/mysql:/var/lib/mysql
    depends_on:
      - php
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: database
      MYSQL_USER: user
      MYSQL_PASSWORD: password
